# python3-truenas-spdk
usr/lib/python*/site-packages/spdk-*.dist-info
usr/lib/python*/site-packages/spdk/*.py
usr/lib/python*/site-packages/spdk/rpc/*.py
dpdk/license/* usr/share/doc/python3-truenas-spdk/dpdk/license
intel-ipsec-mb/LICENSE usr/share/doc/python3-truenas-spdk/intel-ipsec-mb
isa-l/LICENSE usr/share/doc/python3-truenas-spdk/isa-l
isa-l-crypto/LICENSE usr/share/doc/python3-truenas-spdk/isa-l-crypto
libvfio-user/LICENSE usr/share/doc/python3-truenas-spdk/libvfio-user
ocf/LICENSE usr/share/doc/python3-truenas-spdk/ocf
xnvme/LICENSE usr/share/doc/python3-truenas-spdk/xnvme

